#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_{{ .SERVICE_NAME | ToUpper }}_PORT text "Port" 8024
  service::config_set SERVICE_{{ .SERVICE_NAME | ToUpper }}_USERNAME text "Username"
  service::config_set SERVICE_{{ .SERVICE_NAME | ToUpper }}_PASSWORD text "Password"
}

check $@
