#!/bin/bash

which zmicro >>/dev/null 2>&1
if [ $? -ne 0 ]; then
  curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash
fi

if [ "$TESTING" = "true" ]; then
  zmicro service test {{.SERVICE_NAME}}
  exit 0
fi

zmicro service start {{.SERVICE_NAME}}
